[metadata]
name = rimopy-javgat
version = 0.0.9
author = Javier Gatón Herguedas (GOA-UVa)
author_email = javgat@goa.uva.es
description = Rimopy is a package consisting of an implementation of the ROLO model, imitating RIMO, made in python.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://gitlab.com/javgat/rimopy
project_urls =
    Bug Tracker = https://gitlab.com/javgat/rimopy/issues
classifiers =
    Programming Language :: Python :: 3
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.8
include_package_data = True

install_requires = 
    numpy>=1.22.0
    scipy>=1.7.3
    spiceypy>=4.0.3

[options.packages.find]
where = src