[metadata]
name = rimopy
version = 0.2.1
author = Javier Gatón Herguedas
author_email = gaton@goa.uva.es
description = Implementation of the ROLO model, following RIMO’s implementation. Made by the Group of Atmospheric Optics (GOA-UVa) of Universidad de Valladolid
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/GOA-UVa/rimopy
project_urls =
    Bug Tracker = https://github.com/GOA-UVa/rimopy/issues
classifiers =
    Programming Language :: Python :: 3
    Operating System :: OS Independent

[options]
package_dir =
    = .
packages = find:
python_requires = >=3.8
include_package_data = True

install_requires = 
    numpy>=1.22.0    
    spiceypy>=4.0.3
    spicedmoon>=1.0.13

[options.packages.find]
where = .